name: Backend API SDET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run API tests
        env:
          REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}
        run: |
          mkdir -p reports
          python -m pytest -m smoke  \
            --junitxml=reports/junit-smoke.xml \
            --html=reports/smoke-report.html \
            --self-contained-html


      - name: Upload JUnit Test Report
        uses: actions/upload-artifact@v4
        with:
            name: junit-smoke-report
            path: reports/junit-smoke.xml

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v4
        with:
            name: smoke-html-report
            path: reports/smoke-report.html


